### ISSUE TITLE
Feature: handle dependencies and conflicts

### ISSUE THREAD

**Issue by Jocadbz** [Jocadbz/shellpkg#1]
That would make sense.

**Comment by BodgeMaster** [comment]
splitting this issue up into two, dependencies and conflicts here and keeping track of installed packages in a new issue

**Comment by BodgeMaster** [comment]
how to handle conflicts: abort with PACKAGE_ERROR when conflict detected

how to handle dependencies: run `shellpkg-install` for the dependencies one by one recursively, only continue with installation if no errors occurred when installing dependencies

**Comment by Jocadbz** [comment]
This wouldn't make sense to add, since dependencies are appropriate for main package managers...

**Comment by Jocadbz** [comment]
Gonna close this issue.
