### ISSUE TITLE
Complete rewrite of shellpkg in Python

### ISSUE THREAD

**Issue by Jocadbz** [Jocadbz/shellpkg#16]
So... yeah, I'm currently doing this. I am experiencing various bugs, problems that seems unreasonable to me to continue to maintain this package manager in shell script. So, I've decided that i will rewrite it in python, and will open some new possibilities too, such as:
- Ability to install Core packages, such as Desktop environments 
- More speed
- Easy installation
I'm also working on keeping the changes made by @BodgeMaster and @lyiriyah , for example, the config file.
So with that, i am announcing that i will no longer respond to any bugs related to the old shellpkg (now, legacy-shellpkg),
or even try to fix it.

**Comment by lyiriyah** [comment]
Ah good. First thing you should do is decide on a Python version as 3.10 adds the match feature which isn't present in earlier versions

**Comment by Jocadbz** [comment]
Very well, it seems that Python 3.10 isn't packaged yet on Ubuntu, so i might have to wait an little bit

**Comment by Jocadbz** [comment]
Ok, you know what, i'm not waiting. Gonna open an repo soon for general development.

**Comment by Jocadbz** [comment]
Issue closed.
