### ISSUE TITLE
Possibility to add a guide of how host remote packages

### ISSUE THREAD

**Issue by Jocadbz** [Jocadbz/shellpkg#2]
They are pretty basic and can easily be done, but a guide would be cool

**Comment by BodgeMaster** [comment]
Just use a git repo, I suppose. Is that what you are going for?

**Comment by Jocadbz** [comment]
Probably yes. Most people use Github for these kind of things.

**Comment by Jocadbz** [comment]
This issue will be deprecated in favor of issue #11
