### ISSUE TITLE
Incorrect information on README

### ISSUE THREAD

**Issue by arrudagates** [Jocadbz/shellpkg#22]
In your README currently you have a [section title that says `Compiling from source`](https://github.com/Jocadbz/shellpkg/blame/main/README.md#L22), which is incorrect since:
A) The instructions show how to install it and not compile it.
B) Python is an interpreted language.
A possible fix would be to change it to `Installing from source`. A more hardcore solution would be to rewrite the whole thing in a compiled language.

**Comment by Jocadbz** [comment]
Jesus fucking christ

**Comment by Jocadbz** [comment]
No, this is actually valid. Pyinstaller doesn't actually "install" despite the name.  He creates an Linux binary. Therefore, the word "compile" is correct.
