### ISSUE TITLE
Possible Website?

### ISSUE THREAD

**Issue by Jocadbz** [Jocadbz/shellpkg#4]
Would be good for documentation porpouses

**Comment by BodgeMaster** [comment]
I can make one, if you want but I don’t think it’s necessary.

**Comment by Jocadbz** [comment]
> I can make one, if you want but I don’t think it’s necessary.
I kinda want to make one, but i will focus on the issues for now

**Comment by Jocadbz** [comment]
Website is on the works... It's very simple for now... ETA by February next year. (I'm spending my holidays working on it, yikes)

**Comment by Jocadbz** [comment]
Realized that is not necessary. All the features are provided by Github.
