### ISSUE TITLE
Feature: TXT file with metadata of app versions and changelogs

### ISSUE THREAD

**Issue by Jocadbz** [Jocadbz/shellpkg#5]
This would be tricky but not impossible

**Comment by BodgeMaster** [comment]
Pretty easy, actually.

You can just make a file and `cat` or `less` it when appropriate. I will probably add a more complex version of this though.

**Comment by Jocadbz** [comment]
Makes sense. I will close once done.

**Comment by BodgeMaster** [comment]
Let’s just close this issue and make it one with #1.
