### ISSUE TITLE
Write a complete Wiki

### ISSUE THREAD

**Issue by Jocadbz** [Jocadbz/shellpkg#6]

**Comment by Jocadbz** [comment]
Actually I'm writing a guide of how to make your own packages right now.

**Comment by BodgeMaster** [comment]
Uhhhm... Sorry to say that but I already did. It’s in the README.
A configuration guide is still missing but that is easy to add since I wrote it and it’s really primitive. I guess I’ll be adding that to the README.

**Comment by BodgeMaster** [comment]
done
