### ISSUE TITLE
Feature: keep track of installed packages

### ISSUE THREAD

**Issue by BodgeMaster** [Jocadbz/shellpkg#7]
split out from #1

- keep track of what packages are installed and what version if a version string is provided by the package
- when updating, check if version string is available, if it has changed or is not provided by the package, attempt to update (packages that don’t have a version string are assumed to auto-update)

**Comment by BodgeMaster** [comment]
suggestion: add an option `package-db=` in the config

format: `<package>:<installation status>:<version string>

**Comment by Jocadbz** [comment]
Not very hard to do. Requires a little time tho.

**Comment by Jocadbz** [comment]
Seeing the commits looks like it's already done ? Gonna close this.

**Comment by Jocadbz** [comment]
reopened because it's not ready

**Comment by Jocadbz** [comment]
Added with commits f54ccf0 , e4a7bef , and ae9075f
